namespace EcoWittLib.Helper;

/// <summary>
/// generated by claude ai
/// </summary>
public static class EnvironmentCanadaWeather
{
    // Magnus formula constants (Alduchov & Eskridge, 1996)
    private const float MagnusA = 17.625f;
    private const float MagnusB = 243.04f;

    // Dew point valid range
    private const float DewPointMinTempC = -40f;
    private const float DewPointMaxTempC = 60f;

    // Humidex constants
    private const float HumidexMinTempC = 20f;
    private const float HumidexVapourBase = 6.11f;
    private const float HumidexVapourCoefficient = 5417.7530f;
    private const float HumidexKelvinOffset1 = 273.16f;
    private const float HumidexKelvinOffset2 = 273.15f;
    private const float HumidexScale = 0.5555f;
    private const float HumidexVapourThreshold = 10.0f;

    // Wind chill constants (Environment Canada / NWS, 2001)
    private const float WindChillIntercept = 13.12f;
    private const float WindChillTempCoefficient = 0.6215f;
    private const float WindChillWindCoefficient1 = 11.37f;
    private const float WindChillWindCoefficient2 = 0.3965f;
    private const float WindChillWindExponent = 0.16f;
    private const float WindChillMinWindSpeedKmh = 4.8f;
    private const float WindChillMaxWindSpeedKmh = 200f;
    private const float WindChillMaxTempC = 0f;

    // Shared
    private const float HumidityMin = 0f;
    private const float HumidityMax = 100f;
    private const float HumidityDivisor = 100.0f;

    // Formatting
    private const string TemperatureFormat = "F1";

    // -------------------------------------------------------------------------

    private static float CalculateAlpha(float temperatureC, float relativeHumidity) =>
        (MagnusA * temperatureC / (MagnusB + temperatureC))
        + MathF.Log((relativeHumidity / HumidityDivisor));

    public static float CalculateDewPointValue(float temperatureC, float relativeHumidity)
    {
        if (relativeHumidity <= HumidityMin || relativeHumidity > HumidityMax) return temperatureC;
        if (temperatureC < DewPointMinTempC || temperatureC > DewPointMaxTempC) return temperatureC;

        float alpha = CalculateAlpha(temperatureC, relativeHumidity);
        float dewPoint = (MagnusB * alpha) / (MagnusA - alpha);

        return dewPoint;
    }

    public static string CalculateDewPoint(float temperatureC, float relativeHumidity)
    {
        var dewPoint = CalculateDewPointValue(temperatureC, relativeHumidity);

        return MathF.Round(dewPoint, 1).ToString(TemperatureFormat);
    }

    public static string CalculateHumidex(float temperatureC, float relativeHumidity)
    {
        if (temperatureC < HumidexMinTempC) return temperatureC.ToString(TemperatureFormat);
        if (relativeHumidity <= HumidityMin || relativeHumidity > HumidityMax) return temperatureC.ToString(TemperatureFormat);

        float dewPointC = CalculateDewPointValue(temperatureC, relativeHumidity);
        float e = HumidexVapourBase
                          * MathF.Exp((HumidexVapourCoefficient
                          * (1.0f / HumidexKelvinOffset1 - 1.0f / (HumidexKelvinOffset2 + dewPointC))));
        float humidex = temperatureC + HumidexScale * (e - HumidexVapourThreshold);

        if (humidex <= temperatureC) return temperatureC.ToString(TemperatureFormat);

        return MathF.Round(humidex, 1).ToString(TemperatureFormat);
    }

    public static string CalculateWindChill(float temperatureC, float windSpeedKmh)
    {
        if (temperatureC > WindChillMaxTempC) return temperatureC.ToString(TemperatureFormat);
        if (windSpeedKmh <= WindChillMinWindSpeedKmh) return temperatureC.ToString(TemperatureFormat);
        if (windSpeedKmh > WindChillMaxWindSpeedKmh) return temperatureC.ToString(TemperatureFormat);

        float windPow = MathF.Pow(windSpeedKmh, WindChillWindExponent);
        float windChill = WindChillIntercept
                          + (WindChillTempCoefficient * temperatureC)
                          - (WindChillWindCoefficient1 * windPow)
                          + (WindChillWindCoefficient2 * temperatureC * windPow);

        return MathF.Round(windChill, 1).ToString(TemperatureFormat);
    }
}