namespace EcoWittLib.Helper;

/// <summary>
/// generated by claude ai
/// </summary>
public static class EnvironmentCanadaWeather
{
    // Magnus formula constants (Alduchov & Eskridge, 1996)
    private const decimal MagnusA = 17.625m;
    private const decimal MagnusB = 243.04m;

    // Dew point valid range
    private const decimal DewPointMinTempC = -40m;
    private const decimal DewPointMaxTempC = 60m;

    // Humidex constants
    private const decimal HumidexMinTempC = 20m;
    private const decimal HumidexVapourBase = 6.11m;
    private const decimal HumidexVapourCoefficient = 5417.7530m;
    private const decimal HumidexKelvinOffset1 = 273.16m;
    private const decimal HumidexKelvinOffset2 = 273.15m;
    private const decimal HumidexScale = 0.5555m;
    private const decimal HumidexVapourThreshold = 10.0m;

    // Wind chill constants (Environment Canada / NWS, 2001)
    private const decimal WindChillIntercept = 13.12m;
    private const decimal WindChillTempCoefficient = 0.6215m;
    private const decimal WindChillWindCoefficient1 = 11.37m;
    private const decimal WindChillWindCoefficient2 = 0.3965m;
    private const decimal WindChillWindExponent = 0.16m;
    private const decimal WindChillMinWindSpeedKmh = 4.8m;
    private const decimal WindChillMaxWindSpeedKmh = 200m;
    private const decimal WindChillMaxTempC = 0m;

    // Shared
    private const decimal HumidityMin = 0m;
    private const decimal HumidityMax = 100m;
    private const decimal HumidityDivisor = 100.0m;

    // Formatting
    private const string TemperatureFormat = "F1";

    // -------------------------------------------------------------------------

    private static decimal CalculateAlpha(decimal temperatureC, decimal relativeHumidity) =>
        (MagnusA * temperatureC / (MagnusB + temperatureC))
        + (decimal)Math.Log((double)(relativeHumidity / HumidityDivisor));

    public static string CalculateDewPoint(decimal temperatureC, decimal relativeHumidity)
    {
        if (relativeHumidity <= HumidityMin || relativeHumidity > HumidityMax) return temperatureC.ToString(TemperatureFormat);
        if (temperatureC < DewPointMinTempC || temperatureC > DewPointMaxTempC) return temperatureC.ToString(TemperatureFormat);

        decimal alpha = CalculateAlpha(temperatureC, relativeHumidity);
        decimal dewPoint = (MagnusB * alpha) / (MagnusA - alpha);

        return Math.Round(dewPoint, 1).ToString(TemperatureFormat);
    }

    public static string CalculateHumidex(decimal temperatureC, decimal relativeHumidity)
    {
        if (temperatureC < HumidexMinTempC) return temperatureC.ToString(TemperatureFormat);
        if (relativeHumidity <= HumidityMin || relativeHumidity > HumidityMax) return temperatureC.ToString(TemperatureFormat);

        decimal dewPointC = decimal.Parse(CalculateDewPoint(temperatureC, relativeHumidity));
        decimal e = HumidexVapourBase
                          * (decimal)Math.Exp((double)(HumidexVapourCoefficient
                          * (1.0m / HumidexKelvinOffset1 - 1.0m / (HumidexKelvinOffset2 + dewPointC))));
        decimal humidex = temperatureC + HumidexScale * (e - HumidexVapourThreshold);

        if (humidex <= temperatureC) return temperatureC.ToString(TemperatureFormat);

        return Math.Round(humidex, 1).ToString(TemperatureFormat);
    }

    public static string CalculateWindChill(decimal temperatureC, decimal windSpeedKmh)
    {
        if (temperatureC > WindChillMaxTempC) return temperatureC.ToString(TemperatureFormat);
        if (windSpeedKmh <= WindChillMinWindSpeedKmh) return temperatureC.ToString(TemperatureFormat);
        if (windSpeedKmh > WindChillMaxWindSpeedKmh) return temperatureC.ToString(TemperatureFormat);

        decimal windPow = (decimal)Math.Pow((double)windSpeedKmh, (double)WindChillWindExponent);
        decimal windChill = WindChillIntercept
                          + (WindChillTempCoefficient * temperatureC)
                          - (WindChillWindCoefficient1 * windPow)
                          + (WindChillWindCoefficient2 * temperatureC * windPow);

        return Math.Round(windChill, 1).ToString(TemperatureFormat);
    }
}