event:
  - platform: template
    name: "${devicename} Button"
    id: s31_button
    event_types:
      - "pressed"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${devicename} Button"
    on_press:
      - lambda: |-
          id(s31_button).trigger("pressed");
      - script.execute: my_script
  - platform: status
    name: "${devicename} Status"
    id: "${devicename_no_dashes}_status"
    
light:
  - platform: status_led
    id: stat_led
    name: "Switch state"
    pin:
      number: GPIO13
      inverted: yes
      
script:
  - id: my_script
    then:
      - light.turn_off: stat_led
      - delay: 1s
      - repeat:
          count: 60
          then:
            - light.turn_on: stat_led
            - delay: 2s
            - light.turn_off: stat_led
            - delay: 1s   